server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: /springboot-mybatisplus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hxzy?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false  # ???
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false



mybatis-plus:
  mapper-locations: classpath:com/fan/mapper/*.xml
  type-aliases-package: com.fan.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      # ??????
      db-config:
        # ???
        logic-not-delete-value: 1
        # ???
        logic-delete-value: 0