spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
## pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#mybatis:
#  type-aliases-package: com.louis.springboot.demo.model
#  mapper-locations: classpath:com.louis.springboot.demo.sqlmap/*.xml
