server:
  servlet:
    context-path: /libraryManage/

spring:
  application:
    name: /libraryManage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookdb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false  # 不缓存


mybatis-plus:
  mapper-locations: classpath:com/fan/mapper/*.xml
  type-aliases-package: com.fan.entity
